# Generated by Django 5.2.4 on 2025-07-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_auto_20200110_1805"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fobiformwidget",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="page.page",
            ),
        ),
        migrations.AlterField(
            model_name="rawcontent",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="page.page",
            ),
        ),
        migrations.AlterField(
            model_name="richtextcontent",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="page.page",
            ),
        ),
    ]
