# Generated by Django 5.2.4 on 2025-07-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "page",
            "0004_alter_fobiformwidget_parent_alter_rawcontent_parent_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fobiformwidget",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="rawcontent",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="richtextcontent",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
